### ISSUE TITLE
Sponsors: Hide sponsor name from list?

### ISSUE THREAD

**Issue by melchoyce** [bostonwp/wordcamp-2017#5]
These feel repetitive:

![image](https://cloud.githubusercontent.com/assets/2846578/24717679/50749aa6-1a01-11e7-9b57-b7b5480a3654.png)

<img width="739" alt="screen shot 2017-04-05 at 1 10 51 pm" src="https://cloud.githubusercontent.com/assets/2846578/24717684/52333fa0-1a01-11e7-8f95-1b1d07d35fe2.png">

**Comment by ryelle** [comment]
Sounds good — if anyone has a logo that doesn't have their name, we can add it as an header in the post content, maybe?

**Comment by melchoyce** [comment]
Sounds good 👍
